# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/EiPy',
                'doc_host': 'https://flupppi.github.io',
                'git_url': 'https://github.com/flupppi/EiPy',
                'lib_path': 'EiPy'},
  'syms': {'EiPy.core': {'EiPy.core.foo': ('core.html#foo', 'EiPy/core.py')}}}
