# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_network_analysis.ipynb.

# %% auto 0
__all__ = ['plot_linregress_comparison']

# %% ../nbs/05_network_analysis.ipynb 12
def plot_linregress_comparison(x, y, name, ax):
    log_x = np.log10(x)
    log_y = np.log10(y)
    res = stats.linregress(log_x, log_y)
    alpha = -res.slope
    
    
    ax.set_xscale('log')
    ax.set_yscale('log')
    ax.plot(x, y, 'o', label='Original data')
    ax.plot(x, 10**(res.slope * log_x + res.intercept), '--', label=f'Fit: y ~ x^-{alpha:.2f}')
    ax.set_xlabel('x')
    ax.set_ylabel(name)
    ax.set_title(f'Log-log plot of {name}')
    ax.legend()
    ax.grid(True)
    # Print results
    print(f"Estimated power-law exponent {name}: α ≈ {alpha:.2f}")
    print(f"R-squared {name}: {res.rvalue**2:.6f}")
