# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/network analysis.ipynb.

# %% auto 0
__all__ = ['n']

# %% ../nbs/network analysis.ipynb 1
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np

# %% ../nbs/network analysis.ipynb 3
n = 10
