# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_plotsine.ipynb.

# %% auto 0
__all__ = ['plot_sine']

# %% ../nbs/00_plotsine.ipynb 4
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# %% ../nbs/00_plotsine.ipynb 6
def plot_sine(n):
    """plot a sinus function"""
    a: np.ndarray = np.linspace(start=1, stop=n, num=n) / n
    A = np.arange(1, n + 1) / n

    b: np.ndarray = np.sin(2 * np.pi * a)  # Array of sine values based on a
    print(b)
    print(f"Sum of array a: {np.sum(a)}")  # Display sum of array components

    # Plot the sine function with labels and title
    plt.plot(a, b, '-b', label="sin(x)")
    plt.xlabel("x values")
    plt.ylabel("sin(x)")
    plt.title("Sinus Plot")
    plt.legend()
    plt.savefig("sinus.pdf", format="pdf")

    plt.show()

# %% ../nbs/00_plotsine.ipynb 8
plot_sine(100)
